/* Independent demo catalog. Intentionally does not depend on the original files. */
window.STUDIO_COURSES = [
  { id: 'html', title: 'HTML Fundamentals', category: 'Frontend', instructor: 'John Doe', role: 'Frontend engineer', hours: 6, level: 'Beginner', rating: 4.9, students: '2.4k', color: 'peach', symbol: '</>', tag: 'START WITH THE FOUNDATIONS', label: 'Bestseller', description: 'Turn a blank page into something meaningful. Learn to structure accessible, semantic websites with confidence.', topics: ['Your first web page', 'Semantic HTML', 'Links and navigation', 'Forms and accessibility', 'Build a personal page'], outcome: 'Build an accessible personal website from scratch.' },
  { id: 'css', title: 'CSS Essentials', category: 'Frontend', instructor: 'Sarah Smith', role: 'Design engineer', hours: 5, level: 'Beginner', rating: 4.8, students: '1.8k', color: 'lavender', symbol: '{ }', tag: 'MAKE EVERY PIXEL COUNT', label: 'Popular', description: 'Bring your ideas to life with beautiful layouts. Explore the cascade, Flexbox, Grid, and responsive design.', topics: ['The cascade and selectors', 'The box model', 'Layout with Flexbox', 'Responsive CSS Grid', 'Motion and finishing touches'], outcome: 'Create a polished, responsive landing page.' },
  { id: 'javascript', title: 'JavaScript Basics', category: 'Frontend', instructor: 'Mike Johnson', role: 'Software engineer', hours: 8, level: 'Intermediate', rating: 4.9, students: '3.1k', color: 'yellow', symbol: 'JS', tag: 'A LITTLE LOGIC. ENDLESS POSSIBILITIES.', label: 'Bestseller', description: 'Give your websites a life of their own. Work with functions, events, and the DOM to create useful interactions.', topics: ['Values and variables', 'Functions and scope', 'Arrays and objects', 'Working with the DOM', 'Events and interactions'], outcome: 'Build an interactive task manager with JavaScript.' },
  { id: 'aspnet', title: 'ASP.NET Core', category: 'Backend', instructor: 'Emily Davis', role: 'Backend architect', hours: 10, level: 'Intermediate', rating: 4.8, students: '1.2k', color: 'blue', symbol: '.NET', tag: 'BUILD WHAT POWERS THE WEB', label: '', description: 'Go behind the interface and build reliable web applications with routing, middleware, and well-designed APIs.', topics: ['The request pipeline', 'Routing and endpoints', 'Dependency injection', 'Working with data', 'Design a REST API'], outcome: 'Design the foundations of a maintainable REST API.' },
  { id: 'csharp', title: 'C# for Beginners', category: 'Backend', instructor: 'David Wilson', role: 'Senior .NET developer', hours: 8, level: 'Beginner', rating: 4.7, students: '960', color: 'pink', symbol: 'C#', tag: 'YOUR NEXT LANGUAGE STARTS HERE', label: '', description: 'Build a strong programming foundation with C#. Learn types, control flow, and object-oriented thinking.', topics: ['Types and variables', 'Decisions and loops', 'Methods', 'Classes and objects', 'Collections and practice'], outcome: 'Write a small console application with reusable classes.' },
  { id: 'sql', title: 'SQL Fundamentals', category: 'Database', instructor: 'Lisa Brown', role: 'Data engineer', hours: 6, level: 'Beginner', rating: 4.9, students: '1.6k', color: 'mint', symbol: 'SQL', tag: 'GOOD QUESTIONS. BETTER DATA.', label: 'Popular', description: 'Find the story in your data. Learn to query, filter, and connect relational data with practical SQL skills.', topics: ['Tables and relationships', 'Your first SELECT', 'Filtering and sorting', 'Joining tables', 'Grouping and aggregation'], outcome: 'Query a relational database and summarize useful insights.' },
  { id: 'react', title: 'React: From Idea to Interface', category: 'Frontend', instructor: 'Sarah Smith', role: 'Design engineer', hours: 9, level: 'Intermediate', rating: 4.9, students: '840', color: 'blue', symbol: '⚛', tag: 'THINK IN COMPONENTS', label: 'New', description: 'Break big ideas into small, reusable components. Explore props, state, and thoughtful interface composition.', topics: ['Thinking in components', 'Props and composition', 'State and events', 'Lists and forms', 'A complete interface'], outcome: 'Plan and build a component-based project dashboard.' },
  { id: 'api', title: 'Practical API Design', category: 'Backend', instructor: 'Emily Davis', role: 'Backend architect', hours: 7, level: 'Advanced', rating: 4.8, students: '620', color: 'peach', symbol: 'API', tag: 'CONNECT THE POSSIBILITIES', label: 'New', description: 'Design clear, dependable interfaces between systems. Learn resource modeling, validation, and error handling.', topics: ['Resources and contracts', 'HTTP semantics', 'Validation and errors', 'Pagination', 'Document your API'], outcome: 'Write an API contract that developers enjoy using.' },
  { id: 'data', title: 'Database Design Essentials', category: 'Database', instructor: 'Lisa Brown', role: 'Data engineer', hours: 5, level: 'Intermediate', rating: 4.7, students: '710', color: 'lavender', symbol: 'DB', tag: 'A SOLID FOUNDATION FOR YOUR DATA', label: '', description: 'Move from spreadsheets to well-structured data. Model relationships, choose keys, and reduce duplication.', topics: ['Entities and attributes', 'Primary and foreign keys', 'Relationships', 'Normalization', 'Model a learning platform'], outcome: 'Create a relational schema for a learning platform.' }
];

/* Original, short reading lessons: the dashboard needs no video or external service. */
window.STUDIO_LESSONS = {
  html: [
    ['Every page starts with structure', 'HTML describes the meaning and structure of a document. Start with a doctype, a language on the html element, a head for metadata, and a body for visible content. A descriptive page title helps people recognize a page in their tabs.', '<!DOCTYPE html>\n<html lang="en">\n  <head><title>My first page</title></head>\n  <body><h1>Hello, world.</h1></body>\n</html>', 'Create a page with a title, one main heading, and a paragraph about something you want to learn.'],
    ['Choose meaning before appearance', 'Use header, nav, main, and footer to describe the landmarks of a page. Use a button for an action and a link for navigation. Heading levels should describe the content hierarchy; their visual size can be changed with CSS.', '<main>\n  <h1>My learning journal</h1>\n  <section aria-labelledby="goals">\n    <h2 id="goals">This week’s goals</h2>\n    <p>Build something useful.</p>\n  </section>\n</main>', 'Replace generic div containers in your page with meaningful landmarks.'],
    ['Help people find their way', 'Links connect documents and sections. Use descriptive link text so a destination makes sense outside the surrounding paragraph. Relative URLs point to files in your project; a hash points to an element with a matching id.', '<nav aria-label="Main">\n  <a href="index.html">Home</a>\n  <a href="#projects">My projects</a>\n</nav>\n<section id="projects"><h2>Projects</h2></section>', 'Add navigation links to two sections of your personal page.'],
    ['Make inputs understandable', 'A visible label explains what an input expects. Connect the label’s for attribute to the input’s id. Use the right input type, clear instructions, and helpful validation. Placeholders are examples, not replacements for labels.', '<label for="email">Email address</label>\n<input id="email" name="email" type="email" required>\n<button type="submit">Join the newsletter</button>', 'Add a labeled contact form and navigate through it using only your keyboard.'],
    ['Put the pieces together', 'Build a small page with navigation, an introduction, a project list, and a contact section. Check the heading order, meaningful link text, and image alternatives. A solid HTML foundation stays useful when the visual design changes.', '<article>\n  <h2>My first project</h2>\n  <p>A small website with a clear purpose.</p>\n  <a href="project.html">Explore my first project</a>\n</article>', 'Finish your personal page and explain the purpose of each landmark to a friend.']
  ],
  css: [
    ['Understand the cascade', 'CSS rules can compete. The browser resolves them using origin, importance, layers, specificity, and source order. Keep selectors simple and use classes to express reusable visual patterns.', '.card {\n  color: #193d34;\n  background: #ffffff;\n}\n.card-title { font-weight: 700; }', 'Style two cards with the same class, then add a modifier class to one.'],
    ['Everything is a box', 'An element’s box includes content, padding, border, and margin. With border-box, declared width includes padding and border. This makes layout calculations easier to reason about.', '* { box-sizing: border-box; }\n.card {\n  width: 100%;\n  padding: 24px;\n  border: 1px solid #e2e8e4;\n}', 'Inspect a card in browser developer tools and identify each part of its box.'],
    ['Align in one dimension', 'Flexbox arranges items along a main axis. Use gap for spacing, align-items for cross-axis alignment, and flex-wrap when the available space can change. Avoid fixed widths when content needs room to grow.', '.toolbar {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  gap: 16px;\n  flex-wrap: wrap;\n}', 'Build a toolbar that wraps comfortably on a narrow screen.'],
    ['Create layouts that adapt', 'Grid works with rows and columns together. Flexible tracks let content adapt without a breakpoint for every device. Use minmax to protect a useful minimum size and share the remaining space.', '.courses {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(min(100%, 250px), 1fr));\n  gap: 24px;\n}', 'Create a card grid and resize the browser from phone to desktop widths.'],
    ['Make motion considerate', 'Motion should explain a change, not delay an action. Keep transitions subtle, provide visible keyboard focus, and respect the prefers-reduced-motion setting.', 'button:focus-visible { outline: 3px solid #287c65; }\n@media (prefers-reduced-motion: reduce) {\n  * { scroll-behavior: auto; transition: none; }\n}', 'Add a hover transition and a keyboard focus style, then test reduced motion.']
  ],
  javascript: [
    ['Give values a name', 'Use const when a binding does not need reassignment and let when it does. Strings describe text, numbers describe quantities, and booleans express yes-or-no conditions. Choose names that explain the value’s purpose.', 'const learner = "Alex";\nlet completedLessons = 0;\ncompletedLessons += 1;\nconst hasStarted = completedLessons > 0;', 'Create variables for a course title, lesson count, and completion status.'],
    ['Make behavior reusable', 'Functions turn inputs into results or actions. Small functions are easier to understand and verify. Variables declared inside a function belong to its local scope.', 'function progress(completed, total) {\n  if (total === 0) return 0;\n  return Math.round((completed / total) * 100);\n}\nprogress(3, 5); // 60', 'Write a function that formats a learner’s name for a welcome message.'],
    ['Organize related information', 'Objects group named properties. Arrays hold ordered collections. Use map to transform items and filter to keep items that match a condition without changing the original array.', 'const courses = [\n  { title: "HTML", completed: true },\n  { title: "CSS", completed: false }\n];\nconst active = courses.filter(course => !course.completed);', 'Filter a list of courses to return only those you have completed.'],
    ['Connect data to the page', 'The DOM represents a document as objects. Select an element, create content, and update the page. Prefer textContent for plain text so user input is never interpreted as HTML.', 'const heading = document.querySelector("h1");\nheading.textContent = "Your learning space";\nconst item = document.createElement("li");\nitem.textContent = "Practice JavaScript";', 'Create a list item using JavaScript and append it to a list.'],
    ['Respond to real interactions', 'Event listeners run when people interact with the page. Use semantic buttons so keyboard and pointer interactions work together. For forms, handle submit rather than only listening to a button click.', 'const form = document.querySelector("form");\nform.addEventListener("submit", event => {\n  event.preventDefault();\n  const data = new FormData(form);\n  console.log(data.get("task"));\n});', 'Build a form that adds a task to a list without reloading the page.']
  ]
};

// Concise guided readings for the remaining catalog, organized by topic.
const studioReading = {
  aspnet: [
    ['A request passes through middleware before an endpoint returns a response. Middleware order matters: error handling should wrap later operations.', 'app.UseExceptionHandler("/error");\napp.UseRouting();\napp.MapGet("/hello", () => "Hello");', 'Sketch the journey from an HTTP request to its response.'],
    ['Routing matches a request method and URL to a handler. Prefer meaningful resource names and explicit parameters.', 'app.MapGet("/courses/{id:int}", (int id) =>\n  Results.Ok(new { Id = id }));', 'Design routes for listing courses and viewing a single course.'],
    ['Dependency injection provides a class with the services it needs. Interfaces keep implementation details separate from the calling code.', 'builder.Services.AddScoped<ICourseService, CourseService>();', 'Identify which responsibilities should live in a separate service.'],
    ['Keep data access separate from request handling. Validate inputs, use parameterized queries, and handle missing records explicitly.', 'var course = await db.Courses.FindAsync(id);\nreturn course is null ? Results.NotFound() : Results.Ok(course);', 'Describe what an endpoint should return when a course does not exist.'],
    ['A clear API uses consistent resource names, response shapes, and status codes. Plan the contract before connecting it to a frontend.', 'GET /courses\nGET /courses/42\nPOST /enrollments', 'Write an example request and response for enrolling in a course.']
  ],
  csharp: [
    ['C# associates every value with a type. Clear names and appropriate types help the compiler catch mistakes early.', 'string title = "My first course";\nint lessons = 5;\nbool completed = false;', 'Represent a course using three typed variables.'],
    ['Conditions choose a path; loops repeat work. Keep each loop focused and make its ending condition clear.', 'for (int lesson = 1; lesson <= 5; lesson++)\n{\n    Console.WriteLine($"Lesson {lesson}");\n}', 'Print a message for each lesson in a course.'],
    ['Methods name a reusable piece of behavior. A return type describes the result; parameters describe the required inputs.', 'static int Percent(int done, int total)\n{\n    return total == 0 ? 0 : done * 100 / total;\n}', 'Write a method that calculates lessons remaining.'],
    ['A class combines state and behavior. An object is an instance of that class. Expose only what other code needs to use.', 'class Course\n{\n    public string Title { get; set; } = "";\n    public int LessonCount { get; set; }\n}', 'Create two course objects with different titles.'],
    ['A generic List holds a collection of one type. Iterate through it to perform work, and keep data processing separate from presentation.', 'var titles = new List<string> { "HTML", "CSS" };\nforeach (var title in titles)\n    Console.WriteLine(title);', 'Create a console app that lists your learning goals.']
  ],
  sql: [
    ['Tables organize records into rows and attributes into columns. A primary key identifies a record; foreign keys connect related records.', 'courses: id, title, instructor_id\ninstructors: id, name', 'Sketch the relationship between courses and instructors.'],
    ['SELECT retrieves columns from a table. List the columns you need so the result and its purpose are clear.', 'SELECT id, title\nFROM courses;', 'Write a query to retrieve instructor names.'],
    ['WHERE filters rows before the result is returned. ORDER BY makes ordering explicit. Never assume rows have an inherent order.', "SELECT title, hours\nFROM courses\nWHERE hours <= 6\nORDER BY title;", 'Find beginner courses ordered by duration.'],
    ['A join combines records using a relationship. An inner join keeps matching pairs, while a left join also keeps unmatched rows from the left table.', 'SELECT c.title, i.name\nFROM courses AS c\nJOIN instructors AS i ON c.instructor_id = i.id;', 'Explain when a left join would be useful.'],
    ['Aggregate functions summarize groups of records. GROUP BY defines the groups; HAVING filters the grouped results.', 'SELECT category, COUNT(*) AS course_count\nFROM courses\nGROUP BY category;', 'Count the courses in each category.']
  ],
  react: [
    ['Components are reusable pieces of interface. Start by identifying the data each piece needs and the responsibility it owns.', 'function CourseTitle() {\n  return <h2>Start learning</h2>;\n}', 'Break a course card into meaningful components.'],
    ['Props carry data from a parent to a child. Composition keeps components flexible and avoids coupling them to a particular screen.', 'function CourseTitle({ title }) {\n  return <h2>{title}</h2>;\n}', 'Pass two different titles to the same component.'],
    ['State remembers values between renders. Update it with its setter; do not mutate objects or arrays already held in state.', 'const [saved, setSaved] = useState(false);\n<button onClick={() => setSaved(value => !value)}>\n  {saved ? "Saved" : "Save course"}\n</button>', 'Build a favorite button with a visible saved state.'],
    ['Use stable keys when rendering lists. Controlled inputs reflect state, and labels make forms understandable to everyone.', '<ul>\n  {courses.map(course => (\n    <li key={course.id}>{course.title}</li>\n  ))}\n</ul>', 'Render three courses with stable identifiers.'],
    ['Keep shared state at the nearest common parent. Derive filtered lists from the source data instead of storing duplicate copies.', 'const visible = courses.filter(course =>\n  course.title.toLowerCase().includes(query.toLowerCase())\n);', 'Combine a search field and a course list into a small dashboard.']
  ],
  api: [
    ['A resource represents a meaningful concept in your application. Contracts describe accepted input and the response consumers can rely on.', 'GET /courses/42\n{ "id": 42, "title": "HTML Fundamentals" }', 'Define the fields required for a course resource.'],
    ['HTTP methods communicate intent. GET reads, POST commonly creates, PATCH partially updates, and DELETE removes. Status codes describe the outcome.', 'GET /courses → 200 OK\nPOST /enrollments → 201 Created\nGET /courses/unknown → 404 Not Found', 'Choose methods and statuses for three operations.'],
    ['Validate inputs at system boundaries. Return predictable error objects that explain what failed without exposing internal implementation details.', '{\n  "code": "INVALID_INPUT",\n  "message": "Choose an existing course."\n}', 'Write a useful error response for a missing course identifier.'],
    ['Pagination bounds the work done by a request. Use a consistent order and document how clients request the next page.', 'GET /courses?limit=20&after=course_42', 'Explain how a client knows whether another page is available.'],
    ['Useful documentation includes purpose, authentication, parameters, examples, and failure cases. Keep examples consistent with the actual contract.', 'Endpoint: POST /enrollments\nInput: { "courseId": 42 }\nSuccess: 201 with enrollment resource', 'Document one endpoint including both a success and a failure.']
  ],
  data: [
    ['An entity is something your system needs to remember. Attributes describe it. Start with the questions your application must answer.', 'Learner: id, name, email\nCourse: id, title\nEnrollment: learner_id, course_id', 'List the entities in a small learning platform.'],
    ['Primary keys identify rows. Foreign keys preserve relationships by pointing to a valid parent record. Choose keys that remain stable.', 'CREATE TABLE courses (\n  id INTEGER PRIMARY KEY,\n  title VARCHAR(200) NOT NULL\n);', 'Choose a primary key for each entity in your model.'],
    ['Relationships can be one-to-one, one-to-many, or many-to-many. A junction table represents a many-to-many relationship.', 'enrollments\n  learner_id → learners.id\n  course_id → courses.id\n  UNIQUE (learner_id, course_id)', 'Model a learner enrolling in several courses.'],
    ['Normalization reduces duplicated facts. Store an instructor’s name once and reference the instructor from each course. Update a fact in one place.', 'instructors (id, name)\ncourses (id, title, instructor_id)', 'Find a repeated fact in a spreadsheet and move it to its own table.'],
    ['A useful schema reflects real rules. Specify required values, uniqueness, and relationships. Test the model using example records before building it.', 'lesson_progress\n  learner_id\n  lesson_id\n  completed_at\n  UNIQUE (learner_id, lesson_id)', 'Draw a schema that supports courses, lessons, and learner progress.']
  ]
};
for (const course of window.STUDIO_COURSES) {
  if (!window.STUDIO_LESSONS[course.id]) {
    window.STUDIO_LESSONS[course.id] = studioReading[course.id].map((lesson, index) => [course.topics[index], ...lesson]);
  }
}
